name: Build Web and macOS Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    - name: Build Web
      run: npm run build:web
      
    - name: Create web archive
      run: |
        cd dist-web
        zip -r ../web-version.zip *
        cd ..
        echo "Archive size:"
        ls -lh web-version.zip
        
    - name: Upload web artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-version
        path: web-version.zip
        if-no-files-found: error

  build-mac:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    - name: Build macOS App
      run: npm run build:mac
      
    - name: Create macOS artifacts
      run: |
        mkdir -p release
        zip -r release/mac-version.zip release/*.dmg
        echo "macOS build artifact created:"
        ls -lh release/

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mac-version
        path: release/mac-version.zip
        if-no-files-found: error
