name: Build macOS Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build macOS
      run: npm run build:mac

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-version
        path: release/*.dmg
        if-no-files-found: error

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.dmg
        name: macOS Release ${{ github.sha }}
        tag_name: mac-v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          macOS verze aplikace (DMG soubor)
          
          Jak spustit:
          1. Stáhněte soubor .dmg z Release sekce.
          2. Otevřete soubor a přetáhněte aplikaci do složky Aplikace.
          
          Poznámky:
          - Aplikace není podepsaná, při prvním spuštění ji musíte manuálně povolit.
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
