name: Build Web Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    - name: Build Web
      run: npm run build:web
      
    - name: Create server script
      run: |
        cat > dist-web/server.py << 'EOL'
        import http.server
        import socketserver
        import webbrowser
        from pathlib import Path
        
        PORT = 8000
        
        class Handler(http.server.SimpleHTTPRequestHandler):
            def __init__(self, *args, **kwargs):
                super().__init__(*args, directory=str(Path(__file__).parent), **kwargs)
        
        print(f"Starting server at http://localhost:{PORT}")
        print("Opening browser...")
        webbrowser.open(f"http://localhost:{PORT}")
        
        with socketserver.TCPServer(("", PORT), Handler) as httpd:
            print("Server running. Press Ctrl+C to stop.")
            try:
                httpd.serve_forever()
            except KeyboardInterrupt:
                print("\nServer stopped.")
        EOL
        
    - name: Create README
      run: |
        cat > dist-web/README.txt << 'EOL'
        Text2Image Prompt Editor - Web Verze
        
        Pro spuštění aplikace máte dvě možnosti:
        
        1. Pomocí Python serveru (doporučeno):
           - Nainstalujte Python 3 z python.org
           - Spusťte server.py dvojklikem nebo příkazem: python server.py
           - Prohlížeč se automaticky otevře na http://localhost:8000
           
        2. Pomocí VS Code:
           - Otevřete složku ve VS Code
           - Nainstalujte rozšíření "Live Server"
           - Klikněte pravým na index.html a vyberte "Open with Live Server"
        
        Poznámka: Přímé otevření index.html v prohlížeči nebude fungovat kvůli
        bezpečnostním omezením prohlížečů. Musíte použít jednu z výše uvedených metod.
        EOL
        
    - name: List build contents
      run: |
        echo "Web build contents:"
        ls -la dist-web
        echo "Assets:"
        ls -la dist-web/assets
        echo "Total size:"
        du -sh dist-web
        
    - name: Create web archive
      run: |
        cd dist-web
        zip -r ../web-version.zip *
        cd ..
        echo "Archive size:"
        ls -lh web-version.zip
        
    - name: Upload web artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-version
        path: web-version.zip
        if-no-files-found: error

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: web-version.zip
        name: Web Release ${{ github.sha }}
        tag_name: web-v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          Web verze aplikace (web-version.zip)
          
          Instalace:
          1. Stáhněte a rozbalte web-version.zip
          2. Pro spuštění máte dvě možnosti:
             
             a) Pomocí Python serveru (doporučeno):
             - Nainstalujte Python 3 z python.org
             - Spusťte server.py dvojklikem nebo příkazem: python server.py
             - Prohlížeč se automaticky otevře na http://localhost:8000
             
             b) Pomocí VS Code:
             - Otevřete složku ve VS Code
             - Nainstalujte rozšíření "Live Server"
             - Klikněte pravým na index.html a vyberte "Open with Live Server"
          
          Poznámka: Přímé otevření index.html v prohlížeči nebude fungovat kvůli
          bezpečnostním omezením prohlížečů. Musíte použít jednu z výše uvedených metod.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
