name: Build Web Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    - name: Build Web
      run: npm run build:web
      
    - name: Create launch scripts
      run: |
        # Windows .bat script
        cat > dist-web/spustit.bat << 'EOL'
        @echo off
        echo Spouštím aplikaci...
        
        REM Check if Python is installed
        python --version >nul 2>&1
        if %errorlevel% neq 0 (
            echo Python není nainstalován. Stahuji portable verzi...
            powershell -Command "& {Invoke-WebRequest -Uri 'https://www.python.org/ftp/python/3.12.1/python-3.12.1-embed-amd64.zip' -OutFile 'python.zip'}"
            powershell -Command "& {Expand-Archive -Path 'python.zip' -DestinationPath 'python'}"
            del python.zip
            set PYTHON_PATH=%~dp0python\python.exe
        ) else (
            set PYTHON_PATH=python
        )
        
        echo Spouštím server...
        %PYTHON_PATH% -c "import http.server,socketserver,webbrowser,os; PORT=8000; print(f'Server běží na http://localhost:{PORT}'); webbrowser.open(f'http://localhost:{PORT}'); os.chdir(os.path.dirname(os.path.abspath(__file__))); handler=http.server.SimpleHTTPRequestHandler; httpd=socketserver.TCPServer(('', PORT), handler); httpd.serve_forever()"
        EOL
        
        # Mac .command script
        cat > dist-web/spustit.command << 'EOL'
        #!/bin/bash
        cd "$(dirname "$0")"
        echo "Spouštím aplikaci..."
        
        # Check if Python is installed
        if ! command -v python3 &> /dev/null; then
            echo "Python není nainstalován. Otevírám stránku ke stažení..."
            open "https://www.python.org/downloads/"
            echo "Po instalaci Pythonu spusťte tento skript znovu."
            exit 1
        fi
        
        echo "Spouštím server..."
        python3 -c "import http.server,socketserver,webbrowser,os; PORT=8000; print(f'Server běží na http://localhost:{PORT}'); webbrowser.open(f'http://localhost:{PORT}'); os.chdir(os.path.dirname(os.path.abspath(__file__))); handler=http.server.SimpleHTTPRequestHandler; httpd=socketserver.TCPServer(('', PORT), handler); httpd.serve_forever()"
        EOL
        
        # Make Mac script executable
        chmod +x dist-web/spustit.command
        
    - name: Create README
      run: |
        cat > dist-web/README.txt << 'EOL'
        Text2Image Prompt Editor - Web Verze
        
        Spuštění aplikace:
        
        Windows:
        - Dvojklik na spustit.bat
        
        Mac:
        - Dvojklik na spustit.command
        
        Aplikace se automaticky otevře ve vašem výchozím prohlížeči.
        Na Windows se v případě potřeby automaticky stáhne portable verze Pythonu.
        Na Macu budete v případě potřeby přesměrováni na stránku ke stažení Pythonu.
        EOL
        
    - name: List build contents
      run: |
        echo "Web build contents:"
        ls -la dist-web
        echo "Assets:"
        ls -la dist-web/assets
        echo "Total size:"
        du -sh dist-web
        
    - name: Create web archive
      run: |
        cd dist-web
        zip -r ../web-version.zip *
        cd ..
        echo "Archive size:"
        ls -lh web-version.zip
        
    - name: Upload web artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-version
        path: web-version.zip
        if-no-files-found: error

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: web-version.zip
        name: Web Release ${{ github.sha }}
        tag_name: web-v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          Web verze aplikace (web-version.zip)
          
          Spuštění:
          1. Stáhněte a rozbalte web-version.zip
          2. Spusťte:
             - Windows: dvojklik na spustit.bat
             - Mac: dvojklik na spustit.command
          
          Aplikace se automaticky otevře ve vašem výchozím prohlížeči.
          
          Poznámky:
          - Na Windows se v případě potřeby automaticky stáhne portable verze Pythonu
          - Na Macu budete v případě potřeby přesměrováni na stránku ke stažení Pythonu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
